[package]
name = "stork-lib"
version = "1.2.1"
authors = ["James Little <littleguy23@gmail.com>"]
edition = "2018"
documentation = "https://stork-search.net/docs"
homepage = "https://stork-search.net"
description = "Impossibly fast web search, made for static sites."
repository = "https://github.com/jameslittle230/stork"
license = "Apache-2.0"
keywords = ["wasm", "webassembly", "search", "javascript"]
categories = ["wasm"]
exclude = ['/dist/', 'node_modules/', '/test/', '/test-assets/']

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["build-v3"]
read-v2 = ["stork-index-v2"]
read-v3 = ["stork-index-v3"]
build-v3 = ["read-v3", "stork-index-v3/build-local"]
build-v3-web-scraping = ["build-v3", "stork-index-v3/build-web-scraping"]

# test-server = ["build", "futures", "hyper", "tokio"]
# wasm = ["console_error_panic_hook", "wasm-bindgen"]
# cli-timing = ["num-format"]
[dependencies]
bytes = "1.1.0"
colored = { version = "2.0.0" } # colored console output
console_error_panic_hook = { version = "0.1.6", optional = true }
num-format = "0.4.0"
# futures = { version = "0.3", optional = true }
# hyper = { version = "0.14.13", features = ["server", "http1", "tcp"], optional = true }
# indicatif = { version = "0.15.0", optional = true } # progress bar
# num-format = {version = "0.4.0", optional = true }
# once_cell = "1.5.2"
serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"
stork-boundary = { path = "../stork-boundary" }
stork-config = { path = "../stork-config" }
stork-index-v2 = { path = "../stork-index-v2", optional = true, default-features = false }
stork-index-v3 = { path = "../stork-index-v3", optional = true, default-features = false }
stork-shared = { path = "../stork-shared" }
thiserror = "1.0.29"

# tokio = { version = "1.2", features = ["full"], optional = true }
# wasm-bindgen = { version = "=0.2.70", features = ["serde-serialize"], optional = true }
[package.metadata.wasm-pack.profile.release]
# wasm-opt is out of date in wasm-bindgen, so we have to manually
# enable the "mutable globals" feature so wasm-opt doesn't reject
# the wasm blob that gets generated.
# See: https://github.com/rustwasm/wasm-pack/issues/886#issuecomment-667669802
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "basic"
harness = false
