on: push
name: Run CI on Pushes

jobs:
  rust_tests:
    name: "Run Rust Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust environment
        run: |
          cargo install wasm-pack
          cargo install cargo-tarpaulin
          rustup component add rustfmt
      - run: cargo test --verbose
      - run: cargo fmt -- --check
      - name: Upload code coverage
        run: |
          cargo tarpaulin --out Xml
          bash <(curl -s https://codecov.io/bash)
  
  js_tests:
    name: "Run JS Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo install wasm-pack
      - run: wasm-pack build --target web -- --no-default-features
      - run: yarn install
      - run: yarn lint
      - run: yarn test --coverage
      - run: bash <(curl -s https://codecov.io/bash) -cF javascript
  
  clippy_check_nightly:
    name: "Run Clippy Check on Nightly"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup toolchain update nightly && rustup default nightly
      - name: Run benchmark
        run: cd examples/rust && cargo +nightly bench | tee output.txt
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: examples/rust/output.txt
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
          # github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          auto-push: false
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true